### ISSUE TITLE
require checks to pass before git merge

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAI-extra-test-data#3]
@wyli do you think you could have a look at the settings? the [github action works](https://github.com/Project-MONAI/MONAI-extra-test-data/actions/runs/842200352), but the drop-down menu that allows you to choose required checks to pass before merging a pull request is blank.

![image](https://user-images.githubusercontent.com/33289025/118297323-e2245e00-b4d5-11eb-877a-fc6bba46be3f.png)

**Comment by wyli** [comment]
looks like a github issue https://www.githubstatus.com/

**Comment by rijobro** [comment]
Ok, status is green but I still can't add the check. I've created a thread on the github community page here: https://github.community/t/require-status-checks-to-pass-before-merging-missing-status-checks/179921/3.

**Comment by rijobro** [comment]
fixed
